export const defaultSite = {
  brand: {
    name: 'Robotics Club',
    campus: 'BITS Pilani Dubai Campus',
    shortCampus: 'BITS Pilani Dubai',
    logoText: 'RC',
    logoImage: '/images/bits-dubai-campus-logo.webp',
  },
  navigation: [
    { label: 'Home', href: '/' },
    { label: 'Members', href: '/members/council' },
    { label: 'News', href: '/news' },
    { label: 'Lab Facilities', href: '/lab-facilities' },
    { label: 'Contact', href: '/contact' },
  ],
  home: {
    heading: 'Where ideas become machines.',
    description: 'A student-driven space to build, test and explore robotics at BITS Pilani Dubai Campus.',
    primaryLabel: 'Explore the lab',
    primaryHref: '/lab-facilities',
    secondaryLabel: 'Meet the club',
    secondaryHref: '/members/council',
    showcaseLabel: 'Inside the lab',
    newsHeading: 'News & updates',
    newsEmptyTitle: 'No announcements yet.',
    newsEmptyText: 'Club updates will appear here when published.',
  },
  robots: [
    { id: 'arm', title: 'Robotic Arm Workstation', type: 'Manipulation', description: 'Explore precision movement, control and pick-and-place tasks.', image: '/images/robot-arm.jpg', imageAlt: 'Illustrative image of a robotic arm in a lab', imageNote: 'Illustrative concept image' },
    { id: 'mobile', title: 'Mobile Robotics Platform', type: 'Autonomy', description: 'A platform for navigation, mapping and control experiments.', image: '/images/mobile-robot.jpg', imageAlt: 'Illustrative image of a wheeled robot in a lab', imageNote: 'Illustrative concept image' },
    { id: 'vision', title: 'Vision & Sensing Station', type: 'Perception', description: 'Cameras and depth sensors for perception and object detection.', image: '/images/vision-station.jpg', imageAlt: 'Illustrative image of a vision sensing station', imageNote: 'Illustrative concept image' },
  ],
  news: [],
  facilities: [
    { id: 'mobile-facility', name: 'Mobile Robotics Platform', category: 'Navigation', description: 'A wheeled platform for navigation, mapping and control experiments.', image: '/images/mobile-robot.jpg', imageNote: 'Illustrative concept image' },
    { id: 'arm-facility', name: 'Robotic Arm Workstation', category: 'Manipulation', description: 'A multi-axis robotic arm for manipulation and pick-and-place tasks.', image: '/images/robot-arm.jpg', imageNote: 'Illustrative concept image' },
    { id: 'autonomous-facility', name: 'Autonomous Systems Kit', category: 'Prototyping', description: 'Sensors, microcontrollers and boards for building autonomous behaviours.', image: '', imageNote: '' },
    { id: 'vision-facility', name: 'Vision and Sensing Station', category: 'Perception', description: 'Cameras and depth sensors for perception and object detection work.', image: '/images/vision-station.jpg', imageNote: 'Illustrative concept image' },
  ],
  members: [],
  pages: {
    news: { heading: 'News', description: 'Updates and activities from the Robotics Club.' },
    lab: { heading: 'Lab Facilities', description: 'Explore the equipment and areas featured by the Robotics Club.' },
    faculty: { heading: 'Faculty', description: 'The faculty guiding the Robotics Club at BITS Pilani Dubai Campus.' },
    council: { heading: 'Council', description: 'The student council leading the Robotics Club at BITS Pilani Dubai Campus.' },
    contact: { heading: 'Contact', description: 'Get in touch with the Robotics Club at BITS Pilani Dubai Campus.' },
  },
  contact: {
    email: '',
    location: 'BITS Pilani Dubai Campus, Dubai, UAE',
    formHeading: 'Send a message',
    formButton: 'Send message',
    successText: 'Message received. The club will get back to you when possible.',
    social: [],
  },
  footer: { text: 'BITS Pilani Dubai Campus', note: 'A student-led space to build, test and learn.' },
  seo: { title: 'Robotics Club | BITS Pilani Dubai Campus', description: 'The student-driven robotics community at BITS Pilani Dubai Campus.' },
  theme: { accent: '#426c50' },
  ui: {
    headerTagline: 'Build · Test · Learn', homeKicker: 'BITS Pilani Dubai Campus', newsKicker: 'Club news',
    newsReadMore: 'Read more', newsPageEmptyTitle: 'No announcements yet.', newsAllLabel: 'View all updates',
    showcaseEmptyText: 'Lab showcase coming soon.', councilTab: 'Student Council', facultyTab: 'Faculty',
    membersEmptyTitle: 'Meet the people behind the projects.', membersEmptyText: 'Names and profiles will appear here once the club publishes them.',
    labEmptyText: 'Lab details coming soon.', contactDetailsHeading: 'Find us', contactNoEmail: 'Contact details coming soon',
    contactLocationLabel: 'Location', contactEmailLabel: 'Email', contactSocialLabel: 'Follow the club',
    contactNameLabel: 'Name', contactFormEmailLabel: 'Email', contactMessageLabel: 'Message',
  },
};
